"""
CISC7021 Applied Natural Language Processing
Title: Emergent Analogy Reasoning in Tiny LLM
Analogy Ability in Tiny LLM
Simple Conversation Animation
Chat Bot <-> Human User
Skeleton animation code is generated by ChatGPT: https://chatgpt.com/
Modified by Yumu Xie
Credit:
Bot logo comes from: https://es.vecteezy.com/arte-vectorial/10927083-icono-de-chatbot-sobre-fondo-blanco-signo-de-bot-de-servicio-de-soporte-en-linea-signo-de-bot-de-chat-para-el-concepto-de-servicio-de-soporte-estilo-plano
User logo comes from: https://es.vecteezy.com/vectores-gratis/user-icon
"""

import pygame
# import time
from moviepy.video.io.ImageSequenceClip import ImageSequenceClip

# main function
def animation():
    # initialize pygame
    pygame.init()

    # screen settings
    screen_width, screen_height = 800, 400
    screen = pygame.display.set_mode((screen_width, screen_height))
    pygame.display.set_caption("Emergent Analogy Reasoning in Tiny LLM")

    # colors
    WHITE = (255, 255, 255)
    BLACK = (0, 0, 0)
    # BLUE = (0, 128, 255)
    # GREEN = (0, 255, 128)

    # load images
    bot_image = pygame.image.load("./image/bot.jpg")
    user_image = pygame.image.load("./image/user.jpg")

    # resize images to fit the UI
    bot_image = pygame.transform.scale(bot_image, (50, 50))
    user_image = pygame.transform.scale(user_image, (50, 50))

    # font
    font = pygame.font.Font(None, 36)

    # messages
    messages = [
        ("Bot", "Hello! How can I help you today?"),
        ("User", "Can you tell me a joke?"),
        ("Bot", "Why did the Python programmer not respond to the call?"),
        ("Bot", "Because he had no class!"),
        ("User", "Haha, good one!"),
    ]

    # function to draw a message
    def draw_message(role, message, y):
        if role == "Bot":
            # color = BLUE
            image = bot_image
            x_text = 80
        else: # role == "User"
            # color = GREEN
            image = user_image
            x_text = 80
        # text = font.render(f"{role}: {message}", True, color)
        # screen.blit(text, (20, y))
        # draw image and text
        screen.blit(image, (20, y))
        text = font.render(f": {message}", True, WHITE)
        screen.blit(text, (x_text, y + 10)) # offset for better alignment

    # frame storage
    frames = []

    # animation loop
    running = True
    message_index = 0
    y_position = 50
    fps = 120
    frame_delay = fps # number of frames to pause for each message

    while running:
        # background color
        screen.fill(BLACK)

        # quit animation
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

        if message_index < len(messages):
            role, msg = messages[message_index]
            draw_message(role, msg, y_position)
            frame_delay -= 1
            if frame_delay <= 0:
                y_position += 70
                message_index += 1
                # add extra frames to extend the display duration for each message
                for _ in range(fps):
                    frames.append(pygame.surfarray.array3d(screen))
                # reset frame delay
                frame_delay = fps
        else:
            running = False

        # capture frame
        frames.append(pygame.surfarray.array3d(screen))

        # update the entire display surface to the screen
        pygame.display.flip()

    # save the video
    clip = ImageSequenceClip([frame.transpose(1, 0, 2) for frame in frames], fps=fps)
    clip.write_videofile("test_animation.mp4", codec="libx264")

    # quit pygame
    pygame.quit()

if __name__ == "__main__":
    animation()
