"""
CISC7021 Applied Natural Language Processing
Simple Conversation Animation (Prompt Engineering)
Chat Bot <-> Human User
Skeleton code is generated by ChatGPT: https://chatgpt.com/
Modified by Yumu Xie
"""

import pygame
import time

def animation():
    # initialize pygame
    pygame.init()

    # screen settings
    screen_width, screen_height = 800, 400
    screen = pygame.display.set_mode((screen_width, screen_height))
    pygame.display.set_caption("test animation")

    # colors
    WHITE = (255, 255, 255)
    BLACK = (0, 0, 0)
    BLUE = (0, 128, 255)
    GREEN = (0, 255, 128)

    # font
    font = pygame.font.Font(None, 36)

    # messages
    messages = [
        ("Bot", "Hello! How can I help you today?"),
        ("User", "Can you tell me a joke?"),
        ("Bot", "Why did the Python programmer not respond to the call?"),
        ("Bot", "Because he had no class!"),
        ("User", "Haha, good one!"),
        ("N/A", "N/A") # nan message which will not be displayed
    ]

    # function to draw a message
    def draw_message(role, message, y):
        if role == "Bot":
            color = BLUE
        else:
            color = GREEN
        text = font.render(f"{role}: {message}", True, color)
        screen.blit(text, (20, y))

    # animation loop
    running = True
    message_index = 0
    y_position = 50

    while running:
        screen.fill(WHITE)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

        if message_index < len(messages):
            role, msg = messages[message_index]
            draw_message(role, msg, y_position)
            y_position += 50
            message_index += 1
            time.sleep(2) # pause to mimic typing
        else:
            running = False

        pygame.display.flip()

    pygame.quit()

if __name__ == "__main__":
    animation()
